spring:
  datasource:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"

  logging:
    file:
      name: self–°reatorTable.log
      path: /
    level:
      root: ERROR
      ru.jungle.creator.tables.service.TableService: INFO