spring:
  datasource:
    driver: "org.postgresql.Driver"

  logging:
    file:
      name: self–°reatorTable.log
      path: /
    level:
      root: ERROR
      ru.jungle.creator.tables.service.TableService: INFO